# Generated by Django 6.0.3 on 2026-03-31 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave_management.leavetype'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='carry_forward_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type')},
        ),
        migrations.AlterModelTable(
            name='leavebalance',
            table='leave_balances',
        ),
        migrations.AlterModelTable(
            name='leaverequest',
            table='leave_requests',
        ),
        migrations.AlterModelTable(
            name='leavetype',
            table='leave_types',
        ),
    ]
